return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 500,
  tilewidth = 10,
  tileheight = 10,
  nextlayerid = 3,
  nextobjectid = 17,
  properties = {},
  tilesets = {
    {
      name = "food",
      firstgid = 1,
      filename = "food.tsx",
      tilewidth = 10,
      tileheight = 10,
      spacing = 2,
      margin = 0,
      columns = 85,
      image = "../images/food/food.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 10,
        height = 10
      },
      properties = {},
      terrains = {},
      tilecount = 7225,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "food_graphic",
      x = 0,
      y = 0,
      width = 500,
      height = 500,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt20FO22AUhdHLpFKSWWwB9gqArSVZArAgoo47SSRgY/xSB1Wrlqox7cP0HOmOPPlmT7LlBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAao/L5KnteVldAgCc6nyVXLRdrqpLAIBTbdod37bt3HMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgNl76JJ9V10BAEzSJ2d9dQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwOsOQ3IcqisAgCnWY9KN1RUAAAAAAAAAAAAA8JX/VQBg/vyvAgAAAAAAALW+LL7fz54DAO/Xr244ADAfbjkAzN9r79kBgPn58Tv6776rAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvKXDkByH6goAYIr1mHRjdQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDbuVok1203i+oSAOBUt+2O37Xdu+cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwbn3+VF0AAAAAAAAAAAAAAAAAAPD/eeiSfVddAQBM0idnfXUEAAAAAAAAAAAAAADwUT0uk6e252V1CQBwqvNVctF2uaouAQBOtWl3fNu2c88BAAAAAAAAAAAAAAAAAAAAAAAAAACgxGFIjkN1BQAwxXpMurG6AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgm4cu2XfVFQDAJH1y1ldHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/FuPy+Sp7XlZXQKQXC2S67abRXUJzMv5Krlou1xVlwAkt+2O37Xdu+fwRzbtjm/bdu45AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUOgwJMehugIAmGI9Jt1YXQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJzqMCTHoboCAJhiPSbdWF0BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8bYchOQ7VFQDAFOsx6cbqCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4mF4AlUIzBw=="
    },
    {
      type = "objectgroup",
      id = 2,
      name = "food",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3331.5,
          y = 471,
          width = 28,
          height = 26.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4300.36,
          y = 640.909,
          width = 19.2727,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4230.75,
          y = 850.5,
          width = 19,
          height = 19.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2591,
          y = 2351.33,
          width = 28,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1400.55,
          y = 2280.55,
          width = 19.8182,
          height = 20.9091,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 580.182,
          y = 3220.27,
          width = 19.7273,
          height = 19.6364,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480.5,
          y = 3830.5,
          width = 18.75,
          height = 19.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1689.75,
          y = 4410.63,
          width = 20,
          height = 18.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4211.75,
          y = 3580.25,
          width = 25.5,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4020.67,
          y = 2480,
          width = 20,
          height = 18.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928.667,
          y = 1500.33,
          width = 20.6667,
          height = 19.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1790.38,
          y = 790.75,
          width = 19,
          height = 20.125,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
